* Remote desktop
  :PROPERTIES:
  :VISIBILITY: all
  :END:
#+BEGIN_SRC emacs-lisp
(shell-command "start C:\\Users\\donzhu\\Desktop\\donzhu_work.rdp")
(shell-command "start C:\\Users\\donzhu\\Desktop\\donzhu_azure.rdp")
#+END_SRC

* SQL Server Connections
Server=tcp:donzhu.database.windows.net,1433;Initial Catalog=donzhu_db;Persist Security Info=False;User ID={your_username};Password={your_password};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
* search
** symbolhound
http://symbolhound.com/
** english examples
http://www.linguee.fr/francais-anglais/search?source=auto&query=

* MS
** family day
http://suzhoufamilyday/home.html
** hr
*** payslip
https://portal0012.globalview.adp.com/gvolution/home/msft

** ms keys
https://mskeys.microsoft.com/
** visual studio subscription
https://my.visualstudio.com/Benefits?wt.mc_id=o~msft~profile~devprogram_attach&workflowid=devprogram&mkt=en-us
https://my.visualstudio.com/subscriptions
** gift
http://microsoft.ylytbuy.com/cn/myorder.aspx
** kick off
http://stcakickoff/Registration

* UCM
** VSTS
feature board
https://msasg.visualstudio.com/Bing_Ads/UCM%20Team/_backlogs/board/Features 

MSL
https://ucmsz.visualstudio.com/MSL/_backlogs/board/Backlog%20items

Business analytics branches:
https://msasg.visualstudio.com/Bing_Ads/UCM%20Team/_git/UCM-BusinessAnalytics/branches

** SharePoint
https://microsoft.sharepoint.com/teams/BingAds/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FBingAds%2FShared%20Documents%2FTeams%2FUCM

** Zhaojia shared
\\ZHAMA-WORK\shared
** azure link
https://ms.portal.azure.com 
** Wiki
[[https://microsoft.sharepoint.com/teams/BingAds/_layouts/15/WopiFrame2.aspx?sourcedoc={1cafa1d1-25d8-4da7-a2bf-b3a0b6a3fb26}]]
*** glossary
https://microsoft.sharepoint.com/teams/BingAds/_layouts/15/WopiFrame.aspx?sourcedoc={1cafa1d1-25d8-4da7-a2bf-b3a0b6a3fb26}&action=view&wd=target%28%2F%2FWiki%20Home.one%7C027b556a-097e-4010-970b-004bbb0a671d%2FGlossary%7C3a9c5c91-2a68-43f4-8432-bb4d2b056355%2F%29
*** build script
https://microsoft.sharepoint.com/teams/BingAds/_layouts/15/WopiFrame.aspx?sourcedoc={1cafa1d1-25d8-4da7-a2bf-b3a0b6a3fb26}&action=view&wd=target%28%2F%2FDev%20Wiki%2FGetting%20Started.one%7C04b940c5-d538-4cdb-8f62-863a109466e2%2FSetup%20Local%20Env%20By%20Script%7Cb94d8d2f-fd60-4f36-af90-f2abcf3f443f%2F%29
*** architecture
https://microsoft.sharepoint.com/teams/BingAds/_layouts/15/WopiFrame.aspx?sourcedoc={1cafa1d1-25d8-4da7-a2bf-b3a0b6a3fb26}&action=view&wd=target%28%2F%2FDev%20Wiki%2FArchitecture.one%7Cb5bba6cd-3bb4-4830-8f27-2d534c0b01ef%2FOverview%7C22a5bdd7-60b1-4e20-aa47-f23dae1f7e27%2F%29

*** software development lifecycle
https://microsoft.sharepoint.com/teams/BingAds/_layouts/15/WopiFrame.aspx?sourcedoc={1cafa1d1-25d8-4da7-a2bf-b3a0b6a3fb26}&action=view&wd=target%28%2F%2FDev%20Wiki%2FSoftware%20Dev%20Lifecycle.one%7Cf7e473a7-951a-4eab-80e3-e54ed8859aa3%2FOverview%7C2954e48e-3f14-4bd4-9b6c-3e720eeff34a%2F%29

**** Workflow and checking in
https://microsoft.sharepoint.com/teams/BingAds/_layouts/15/WopiFrame.aspx?sourcedoc={1cafa1d1-25d8-4da7-a2bf-b3a0b6a3fb26}&action=view&wd=target%28%2F%2FDev%20Wiki%2FSoftware%20Dev%20Lifecycle.one%7Cf7e473a7-951a-4eab-80e3-e54ed8859aa3%2FWorkflow%20and%20Checking%20In%7Cb20cbeae-d7f4-459f-98f4-8a67d9c3b695%2F%29

**** build and test
https://microsoft.sharepoint.com/teams/BingAds/_layouts/15/WopiFrame.aspx?sourcedoc={1cafa1d1-25d8-4da7-a2bf-b3a0b6a3fb26}&action=view&wd=target%28%2F%2FDev%20Wiki%2FSoftware%20Dev%20Lifecycle.one%7Cf7e473a7-951a-4eab-80e3-e54ed8859aa3%2FBuild%20%20Test%7Cd559978f-d429-4baf-9f3e-4a8f23b53018%2F%29

*** release process
https://microsoft.sharepoint.com/teams/BingAds/_layouts/15/WopiFrame.aspx?sourcedoc={1cafa1d1-25d8-4da7-a2bf-b3a0b6a3fb26}&action=view&wd=target%28%2F%2FDev%20Wiki%2FDRI.one%7Cb136ed15-4ec4-4861-a065-ec69f9ac8c7b%2FUCM%20Release%20Process%7C4d49fc3d-6501-4670-8de2-4838105d0f66%2F%29

*** team process overview
https://microsoft.sharepoint.com/teams/BingAds/_layouts/15/WopiFrame.aspx?sourcedoc={1cafa1d1-25d8-4da7-a2bf-b3a0b6a3fb26}&action=view&wd=target%28%2F%2FDev%20Wiki%2FTeam%20Process.one%7C9f5551f1-259b-454b-90be-e02c81cefd46%2FOverview%7Cba249cf8-cc25-418f-999a-e0f9e3b6111e%2F%29

*** meeting, design, code review
https://microsoft.sharepoint.com/teams/BingAds/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FBingAds%2FShared%20Documents%2FTeams%2FUCM%2FDevelopment%2FMeeting%20-%20Design%2C%20Code%20Review%2C%20Idea

*** shiproom
https://microsoft.sharepoint.com/teams/BingAds/_layouts/15/WopiFrame.aspx?sourcedoc=%7B6DBB5D7C-68D9-4BB1-8A8A-46FFD1A6ABD1%7D&file=UCM%20Shiproom&action=default
** UCM Team process
https://microsoft.sharepoint.com/teams/BingAds/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FBingAds%2FShared%20Documents%2FTeams%2FUCM%2FTeam%20Process

** Prod user request
https://microsoft.sharepoint.com/teams/BingAds/_layouts/15/WopiFrame.aspx?sourcedoc={1cafa1d1-25d8-4da7-a2bf-b3a0b6a3fb26}&action=view&wd=target%28%2F%2FDev%20Wiki%2FGetting%20Started.one%7C04b940c5-d538-4cdb-8f62-863a109466e2%2FUCM%20Prod%20User%20Request%7Cd0c88f6f-c39a-4537-acd7-861c7f7b2773%2F%29

http://admaps/User

** Kendo
** repositories
https://msasg.visualstudio.com/DefaultCollection/Bing_Ads/_admin/_versioncontrol?_a=security

*** router
http://docs.telerik.com/kendo-ui/framework/spa/router

** dev tools
\\products\PUBLIC\PRODUCTS\Developers\

** database connections
https://microsoft.sharepoint.com/teams/BingAds/_layouts/OneNote.aspx?id=%2Fteams%2FBingAds%2FShared%20Documents%2FTeams%2FUCM%2FWiki%2FUCM%20Wiki&wd=target%28Dev%20Wiki%2FArchitecture.one%7CB5BBA6CD-3BB4-4830-8F27-2D534C0B01EF%2FAzure%20Services%5C%2FMachines%7C7DF7BB2E-9C90-44D0-AD45-54D946E8FAAC%2F%29

GME permission:
https://microsoft.sharepoint.com/teams/BingAds/_layouts/OneNote.aspx?id=%2Fteams%2FBingAds%2FShared%20Documents%2FTeams%2FUCM%2FWiki%2FUCM%20Wiki&wd=target%28Teams%2FR%2BD%2FHome.one%7C05E49AF3-7CD1-461A-A705-05B80044AE42%2FRequest%20GEM%20permisson%7CA875CE2B-8229-4E1F-9D82-338C102405CF%2F%29

** DRI
https://icm.ad.msft.net/imp/v3/oncall/current
* Github
https://github.com/dongjiu/.emacs.d
https://github.com/dongjiu/tools4win

* Windows
https://stackoverflow.com/questions/21754255/cmd-command-user-name

** win 10
https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk
https://superuser.com/questions/321988/how-do-i-determine-if-my-windows-is-32-bit-or-64-bit-using-a-command

http://landinghub.visualstudio.com/visual-cpp-build-tools

** redirect stderr to null
https://stackoverflow.com/questions/4507312/how-to-redirect-stderr-to-null-in-cmd-exe

Your DOS command 2> nul

** disable cortana
https://www.pcworld.com/article/2949759/windows/killing-cortana-how-to-disable-windows-10s-info-hungry-digital-assistant.html
https://www.windowscentral.com/how-turn-cortana-and-stop-personal-data-gathering-windows-10
** cmd encoding
command chcp
https://stackoverflow.com/questions/1259084/what-encoding-code-page-is-cmd-exe-using
** telnet missing
http://www.xitongcheng.com/jiaocheng/win10_article_17405.html
** 7z command line example
https://www.dotnetperls.com/7-zip-examples

* Typescript
** backtick '`'
https://basarat.gitbooks.io/typescript/docs/template-strings.html

* emacs
** os bits
https://emacs.stackexchange.com/questions/11052/how-to-determine-operating-system-bits-32-vs-64-bit-in-elisp

** shell-command-to-string exit code
https://stackoverflow.com/questions/23299314/finding-the-exit-code-of-a-shell-command-in-elisp
** font
Chinese font
http://blog.sina.com.cn/s/blog_4d2bb0b10101272j.html
** elisp
*** system environment
https://www.gnu.org/software/emacs/manual/html_node/elisp/System-Environment.html#System-Environment
*** unhighlight region
https://stackoverflow.com/questions/7496397/about-elisps-highlight-region

*** check if a function exists
http://ergoemacs.org/emacs/elisp_check_defined.html
** hooks
https://www.gnu.org/software/emacs/manual/html_node/elisp/Standard-Hooks.html

https://www.reddit.com/r/emacs/comments/2au7t4/split_window_after_creating_frame/
** org
*** use cases
http://kitchingroup.cheme.cmu.edu/blog/2014/08/08/What-we-are-using-org-mode-for/
*** presentation
http://sachachua.com/blog/2013/04/how-to-present-using-org-mode-in-emacs/
*** add link type
http://endlessparentheses.com/use-org-mode-links-for-absolutely-anything.html

*** hide text
https://stackoverflow.com/questions/9879462/how-can-one-hide-some-text-from-being-published-by-the-org-publish-functions

*** presentation
http://jr0cket.co.uk/2013/10/create-cool-slides--Org-mode-Revealjs.html

http://orgmode.org/worg/org-tutorials/non-beamer-presentations.html#S5
*** api
https://emacs.stackexchange.com/questions/17622/how-can-i-walk-an-org-mode-tree

https://emacs.stackexchange.com/questions/35042/parsing-an-orgmode-file-with-org-element-parse-buffer
** package
https://stackoverflow.com/questions/20541322/how-to-remove-installed-elpa-package
** windows
*** png
https://stackoverflow.com/questions/2650041/emacs-under-windows-and-png-files

https://stackoverflow.com/questions/28920230/emacs-24-4-1-image-support-cant-find-libpng16-dll-binary
https://sourceforge.net/projects/ezwinports/files/libpng-1.6.12-w32-bin.zip/download

https://www.wisdomandwonder.com/article/5647/enabling-png-jpg-and-gif-in-emacs-on-windows

https://emacs.stackexchange.com/questions/5994/emacs-doesnt-display-jpeg-files-correctly
https://www.gtk.org/download/windows.php
http://www.msys2.org/
https://sourceforge.net/projects/msys2/
(cdr (assq 'png dynamic-library-alist))
(zlib-available-p)
(image-type-available-p 'png)

  To install the optional libraries, start the MSYS2 Bash window and
  type the following command:

    pacman -S PACKAGES

  where PACKAGES is the list of packages you want to install.  The
  full list is as follows:

  mingw-w64-x86_64-giflib
  mingw-w64-x86_64-gnutls
  mingw-w64-x86_64-libjpeg-turbo
  mingw-w64-x86_64-libpng
  mingw-w64-x86_64-librsvg
  mingw-w64-x86_64-libtiff
  mingw-w64-x86_64-libxml2
  mingw-w64-x86_64-xpm-nox

  You can type any subset of this list.  Once again, when asked
  whether to proceed with installation, answer Y.

** msys2
https://sourceforge.net/p/emacsbinw64/wiki/Build%20guideline%20for%20MSYS2-MinGW-w64%20system/
** sytanx highlighting source code to html
http://ergoemacs.org/emacs/elisp_htmlize.html
https://www.emacswiki.org/emacs/Htmlize

** connect to sql server
https://stackoverflow.com/questions/299512/how-do-i-connect-to-sql-server-using-emacs

** eshell redirect
echo "hello world" > #<buffer universal-greeting>

https://www.emacswiki.org/emacs/EshellRedirection

** inline image in org mode
- Image related dlls are required
- "file:" prefix is required
C-c C-x C-v

https://emacs.stackexchange.com/questions/10114/org-mode-no-images-to-display-inline
** only search visible content in org
https://emacs.stackexchange.com/questions/3929/make-isearch-skip-folded-content-in-org-mode

While using isearch you can toggle the search on invisible text with
M-s i.

** check directory exists
https://emacs.stackexchange.com/questions/34392/how-to-check-if-a-directory-exists-in-elisp/34394
file-directory-p
* .NET
** ASP.NET MVC
*** Bundle
http://www.tutorialsteacher.com/mvc/scriptbundle-mvc

*** Specify layout file:
https://stackoverflow.com/questions/5161380/how-do-i-specify-different-layouts-in-the-asp-net-mvc-3-razor-viewstart-file
*** Controller, Action
[[https://msdn.microsoft.com/en-us/library/dd410269(v=vs.100).aspx]]
*** ViewData, ViewBag
https://stackoverflow.com/questions/4705426/whats-the-difference-between-viewdata-and-viewbag
*** File
https://stackoverflow.com/questions/13983190/actionresult-returning-a-stream
https://stackoverflow.com/questions/8897458/asp-net-download-file-to-client-browser
https://stackoverflow.com/questions/186062/can-an-asp-net-mvc-controller-return-an-image
https://stackoverflow.com/questions/20508788/do-i-need-content-type-application-octet-stream-for-file-download
https://stackoverflow.com/questions/35237863/download-file-using-mvc-core

https://weblogs.asp.net/imranbaloch/custom-actionresult-aspnet5-mvc6

https://stackoverflow.com/questions/12365534/launch-download-in-the-same-tab-without-opening-new-tab-or-window-in-javascript

** C# Console UTF8
Console.OutputEncoding = Encoding.UTF8;

https://stackoverflow.com/questions/2062875/show-utf8-characters-in-console
** Format number
*** padding
https://stackoverflow.com/questions/9587819/c-sharp-padding-amount-with-zeros
https://stackoverflow.com/questions/8293392/format-decimal-value-to-string-with-leading-spaces
** Parse date
https://stackoverflow.com/questions/341175/datetime-parse-and-making-it-work-with-a-specific-format
** LINQ aggregate
https://www.dotnetperls.com/aggregate
** MEF
https://docs.microsoft.com/en-us/dotnet/framework/mef/
** delete directory
[[https://msdn.microsoft.com/en-us/library/fxeahc5f(v=vs.110).aspx]]
Directory.Delete
** delegate invocation can be simplified
https://www.andyheathershaw.uk/2016/11/delegate-invocation-can-be-simplified-c/
** unix time stamp
https://stackoverflow.com/questions/2883576/how-do-you-convert-epoch-time-in-c
** download file
[[https://msdn.microsoft.com/en-us/library/12s31dhy(v=vs.110).aspx]]
https://stackoverflow.com/questions/8897458/asp-net-download-file-to-client-browser
* SQL Server
** connection string
server vs data source
https://stackoverflow.com/questions/15025055/server-vs-data-source-in-connection-string

** randomly select rows
https://stackoverflow.com/questions/848872/select-n-random-rows-from-sql-server-table

** trusted connection
https://stackoverflow.com/questions/1250552/what-is-a-trusted-connection
** set nocount
https://docs.microsoft.com/en-us/sql/t-sql/statements/set-nocount-transact-sql
** format sqlcmd output
https://stackoverflow.com/questions/10561961/formatting-output-in-sqlcmd-mode

sqlcmd -S server -U usr -P pwd -d database
    -h -1 -s "," -W
    -Q \"select * from some_table\"
** quote string
https://docs.microsoft.com/en-us/sql/t-sql/functions/quotename-transact-sql
** insert vbinary
https://stackoverflow.com/questions/1120689/how-can-i-insert-binary-file-data-into-a-binary-sql-field-using-a-simple-insert
** .NET upload file to sql server
https://www.codeproject.com/Articles/308552/Upload-and-Download-Files-to-SQL-Servers-in-ASP-Ne
** datetime
https://stackoverflow.com/questions/1334143/datetime2-vs-datetime-in-sql-server
** varchar(max) vs text
https://stackoverflow.com/questions/834788/using-varcharmax-vs-text-on-sql-server
** sqlcmdvariable
http://sqlblog.com/blogs/jamie_thomson/archive/2012/12/10/editing-sqlcmdvariable-nodes-in-ssdt-publish-profile-files-using-msbuild.aspx
** convert vbinary
https://blogs.msdn.microsoft.com/sqltips/2008/07/02/converting-from-hex-string-to-varbinary-and-vice-versa/
https://stackoverflow.com/questions/14145904/sql-server-hex-string-to-varbinary-conversion
** read vbinary into file
https://stackoverflow.com/questions/4056050/script-to-save-varbinary-data-to-disk
http://www.jitendrazaa.com/blog/sql/sqlserver/export-documents-saved-as-blob-binary-from-sql-server/

** nvarchar vs varchar
https://stackoverflow.com/questions/144283/what-is-the-difference-between-varchar-and-nvarchar
** bulk insert
https://www.red-gate.com/simple-talk/sql/learn-sql-server/bulk-inserts-via-tsql-in-sql-server/
https://weblogs.asp.net/aghausman/saving-and-retrieving-file-using-filestream-sql-server-2008
https://stackoverflow.com/questions/7474862/insert-a-client-file-into-a-column-on-a-server-database
http://www.dotnetspark.com/kb/2052-sql-server-blob-data-net--tutorial.aspx

** large objects
http://www.developer.com/net/asp/article.php/3761486/Working-with-Binary-Large-Objects-BLOBs-Using-SQL-Server-and-ADONET.htm
** ADO.NET
*** large value
[[https://msdn.microsoft.com/en-us/library/a1904w6t(VS.80).aspx]]
*** sql server
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ado-net-code-examples#sqlclient
** Kimball vs Inmon
http://tdan.com/data-warehouse-design-inmon-versus-kimball/20300

** tabular model
https://www.mssqltips.com/sqlservertip/2821/getting-started-with-tabular-model-in-sql-server-2012--part-1/
** MDX
*** and/or
http://www.sqlblogspot.com/2013/10/mdx-where-clause-slicer-axis-andor.html
*** more than two axes
https://stackoverflow.com/questions/380616/how-to-use-3rd-dimension-in-mdx-query-on-pages-syntax
*** hierarchy already appears in the axis0 axis
https://stackoverflow.com/questions/12964203/mdx-error-hierarchy-already-appears-in-the-axis0-axis
*** non null records
https://stackoverflow.com/questions/20569672/mdx-query-for-getting-the-non-null-value-records
*** cross join
http://www.databasejournal.com/features/mssql/article.php/10894_3334631_2/MDX-Essentials-Basic-Set-Functions-The-CrossJoin-Function.htm
https://docs.microsoft.com/en-us/sql/mdx/crossjoin-mdx
*** ampersand
http://blog-mstechnology.blogspot.jp/2010/11/pupose-of-ampersand-character-in-mdx.html
*** members, tuples, and sets
http://www.olapcube.com/mdxhelp/MembersTuplesSets.htm
** DAX
http://www.sqlservercentral.com/articles/DAX/92740/
** ADOMD.NET
*** CellSet
https://docs.microsoft.com/en-us/sql/analysis-services/multidimensional-models-adomd-net-client/retrieving-data-using-the-cellset

** data warehouse concepts
http://www.1keydata.com/datawarehousing/molap-rolap.html

** collation vs nvarchar
https://stackoverflow.com/questions/9756769/what-is-the-point-of-collations-for-nvarchar-unicode-columns

set collation
https://docs.microsoft.com/en-us/sql/relational-databases/collations/set-or-change-the-database-collation

ALTER DATABASE donzhu_db SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

ALTER DATABASE donzhu_db
COLLATE SQL_Latin1_General_CP1_CS_AS;

ALTER DATABASE CURRENT COLLATE SQL_Latin1_General_CP1_CS_AS;

SQL_Latin1_General_CP1_CI_AS
SQL_Latin1_General_CP1_CS_AS

ALTER COLUMN Name VARCHAR(50)  
COLLATE SQL_Latin1_General_CP1_CS_AS 

SELECT Name 
FROM MyTable
WHERE Name = 'CASE' COLLATE SQL_Latin1_General_CP1_CI_AS -- Use case insensitive coll.

** sqlpackage.exe
https://www.mssqltips.com/sqlservertip/4759/sql-server-database-schema-synchronization-via-sqlpackageexe-and-powershell/
https://blogs.msdn.microsoft.com/azuresqldbsupport/2017/01/31/using-sqlpackage-to-import-or-export-azure-sql-db/
[[https://msdn.microsoft.com/en-us/library/hh550080(v=vs.103).aspx

https://dba.stackexchange.com/questions/53033/sqlpackage-exe-ignoring-blockonpossibledataloss]]
* Analysis Services
** tools
*** C# process cube:
Microsoft.AnalysisServices library,
https://stackoverflow.com/questions/2779077/component-for-processing-cube

https://msdn.microsoft.com/en-us/library/mt436122.aspx

https://docs.microsoft.com/en-us/sql/analysis-services/multidimensional-models/analysis-management-objects/developing-with-analysis-management-objects-amo

*** process
https://docs.microsoft.com/en-us/sql/analysis-services/multidimensional-models/tools-and-approaches-for-processing-analysis-services

https://docs.microsoft.com/en-us/sql/analysis-services/multidimensional-models/remote-processing-analysis-services

https://bpmsbi.wordpress.com/2009/12/10/7-ways-to-process-analysis-services/

Command line tool *ascmd*
[[https://msdn.microsoft.com/en-us/library/ms365187.aspx?ranMID=24542&ranEAID=TnL5HPStwNw&ranSiteID=TnL5HPStwNw-0r2NmQ83hbeueRZwkIYQ2A&tduid=(26d69e2b0588c7395d50432061afeaab)(256380)(2459594)(TnL5HPStwNw-0r2NmQ83hbeueRZwkIYQ2A)()]]
* Reveal JS
https://github.com/hakimel/reveal.js
* html
** disable href link
https://stackoverflow.com/questions/5376444/how-do-i-disable-a-href-link-in-javascript

** pop up
https://stackoverflow.com/questions/1328723/how-to-generate-a-simple-popup-using-jquery

** input remeber text
https://stackoverflow.com/questions/16444496/make-text-input-fields-remember-previously-entered-data
https://www.labnol.org/software/force-browser-to-remember-passwords/28472/
http://html.com/attributes/input-autocomplete/

** form ajax
https://stackoverflow.com/questions/5437171/with-javascript-and-ajax-do-i-still-need-the-html-form-tag-and-do-i-still-nee
** dl dt dd
http://www.w3school.com.cn/tags/tag_dl.asp
** viewport
https://www.w3schools.com/css/css_rwd_viewport.asp
* css
** centering
https://www.w3.org/Style/Examples/007/center.en.html
https://stackoverflow.com/questions/7720730/how-to-align-the-absolute-position-to-center
https://www.sitepoint.com/css-center-position-absolute-div/
** overflow: hidden moves text upwards
https://stackoverflow.com/questions/20566710/overflowhidden-displayinline-block-moves-text-upwards

vertical-align: bottom

Root cause: the inline-block element has height equal to its parent
and overflow: hidden causes its bottom edge to be aligned on the text
baseline of the parent. As a result the space that is available for
descenders on the text is essentially doubled.

** anchor remove underline
https://stackoverflow.com/questions/2041388/how-to-remove-the-underline-for-anchorslinks
text-decoration: none;
** <li> remove bullets
https://stackoverflow.com/questions/18028741/removing-bullets-from-unordered-list-ul
ul { list-style-type: none; }
** div takes up all vertical space
https://stackoverflow.com/questions/12443983/make-a-div-take-up-all-available-vertical-space
** inline-block unwanted space
https://stackoverflow.com/questions/5256533/a-space-between-inline-block-list-items
** table border
https://stackoverflow.com/questions/7764553/how-do-i-set-table-border-width-with-css
** table scroll bar
https://stackoverflow.com/questions/14834198/table-scroll-with-html-and-css
https://stackoverflow.com/questions/5533636/add-horizontal-scrollbar-to-html-table
** font
微软雅黑
http://www.cnblogs.com/mm2015/p/5919073.html

* life
** credit card
score
https://club.bankcomm.com/customer/index.htm
>>>>>>> Stashed changes

* javascript
** jquery
*** custom events
https://learn.jquery.com/events/introduction-to-custom-events/
*** synchronized call
https://stackoverflow.com/questions/6685249/jquery-performing-synchronous-ajax-requests

function getRemote() {
    return $.ajax({
        type: "GET",
        url: remote_url,
        async: false
    }).responseText;
}
** detecting keys
https://stackoverflow.com/questions/37557990/detecting-combination-keypresses-control-alt-shift
*** each
http://www.w3school.com.cn/jquery/traversing_each.asp
*** hide, show
https://stackoverflow.com/questions/239207/how-does-jquery-implement-hide-and-show
display: none
* openssl
** encrypt/decrypt files
https://stackoverflow.com/questions/16056135/how-to-use-openssl-to-encrypt-decrypt-files

http://www.czeskis.com/random/openssl-encrypt-file.html

** message "writing RSA key"
https://stackoverflow.com/questions/16608154/openssl-how-to-disable-writing-rsa-key-message-in-console
* common knowledge
** time zone
*** abbreviations
https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations
*** ISO 8601
https://en.wikipedia.org/wiki/ISO_8601
* perl
** delete file
unlink
https://perlmaven.com/how-to-remove-copy-or-rename-a-file-with-perl
** catch warning
https://perlmaven.com/how-to-capture-and-save-warnings-in-perl
** DBI truncate
DBD::ODBC::st fetchrow_hashref failed: st_fetch/SQLFetch (long truncated DBI attribute LongTruncOk not set and/or LongReadLen too small) (SQL-HY000) [state was HY000 now 01004]
[Microsoft][ODBC SQL Server Driver]String data, right truncation (SQL-01004) at test_dbi.pl line 13.

https://stackoverflow.com/questions/12315397/database-fetchrow-array-failed-long-truncated-dbi-attribute

https://docstore.mik.ua/orelly/linux/dbi/ch06_02.htm

** binary file
http://www.devx.com/DevX/Tip/17116
https://stackoverflow.com/questions/9765423/open-a-file-in-binary-mode-and-verify-that-the-file-ends-with-a-specified-string
** base64
https://stackoverflow.com/questions/19658314/how-do-i-convert-a-base64-encoded-file-using-perl
https://stackoverflow.com/questions/11301854/perl-convert-image-to-base64
** read
http://www.tutorialspoint.com/perl/perl_read.htm

** append to file
https://perlmaven.com/appending-to-files
** unix timestamp
https://stackoverflow.com/questions/15064446/convert-unix-timestamp-to-a-readable-date-in-perl
** blob
https://www.experts-exchange.com/questions/26218018/Perl-Win32-ODBC-or-DBI-insert-blob-into-MSSQL-2005.html
https://stackoverflow.com/questions/3574812/insert-blob-into-ms-sql-db-using-perl-script
* GPG
** example
http://www.spywarewarrior.com/uiuc/gpg/gpg-com-4.htm
http://edoceo.com/cli/gpg

** inline gpg
http://josefsson.org/inline-openpgp-considered-harmful.html

** expiration
http://www.g-loaded.eu/2010/11/01/change-expiration-date-gpg-key/

** emacs and gpg
https://www.masteringemacs.org/article/keeping-secrets-in-emacs-gnupg-auth-sources

** org mode
https://nakkaya.com/2009/11/19/keeping-secrets-with-emacs-and-gpg/
** emacs prompts untrusted key
https://superuser.com/questions/366035/how-can-i-disable-prompt-about-trust-when-encrypting-file-with-gpg-in-emacs
* markdown
** strikethrough
https://webapps.stackexchange.com/questions/14986/strikethrough-with-github-markdown
** telecom
http://jf.189.cn/selfcenter/order.aspx
* life
** electric charge
http://www.95598.cn/person/index.shtml
* hack
** note3 n9009 root
https://www.muzisoft.com/root/93498.html
* standards
** url escape
https://www.werockyourweb.com/url-escape-characters/
* power bi
** azure analysis services
*** The server parameter must be a valid hostname or HTTP URL.
Make sure you have the latest Power BI Desktop installed.

In Power BI Desktop, make sure you are using the correct
authentication type (Organizational account).

File -> Options -> Data source settings -> Global permissions.

Then see if you spot your asazure:// data source listed.  If so, left
click it then click the Clear Permissions button.  That will cause
Power BI Desktop to prompt you for credentials next time.  This way
you can ensure you choose the proper authentication.  If your
asazure:// data source isn't there, move on to the next step.

Click Get Data and choose Analysis Services. Paste in your asazure://
into the Server textbox and check Import and click OK. On the next
screen choose the Organizational Account tab on the left. Then click
Sign in and choose an Azure Active Directory account (Organizational
account) which has permissions to your model. Then click Connect.

https://stackoverflow.com/questions/41583929/i-am-getting-an-error-while-connecting-to-azure-ssas-server-in-power-bi-through
* visual studio
** vsix
https://stackoverflow.com/questions/25906944/visual-studio-does-not-install-vsix-files
** shortcut
http://www.dofactory.com/reference/visual-studio-shortcuts
* azure
** vm
https://ms.portal.azure.com/#resource/subscriptions/98f9acc0-905d-440f-b811-bf498e235114/resourceGroups/donzhu-group/providers/Microsoft.Compute/virtualMachines/donzhuwin/overview

dongjiu.southcentralus.cloudapp.azure.com

13.84.174.115
** remote desktop - audio service is not running
https://techcommunity.microsoft.com/t5/Compute/Audio-device-not-available-on-MS-Azure-VM/td-p/67770

** data factory
*** import data factory to visual studio
Use "Cloud Explorer" in visual studio.
http://www.sqlservercentral.com/articles/Azure+Data+Factory/139478/
https://marketplace.visualstudio.com/items?itemName=MicrosoftCloudExplorer.CloudExplorerforVisualStudio2015#review-details
https://stackoverflow.com/questions/31586439/missing-azure-components-in-visual-studio-2015-server-explorer

** ping
https://superuser.com/questions/611216/cant-ping-8-8-8-8-from-virtual-machine-in-azure
** centos
http://52.187.112.52/
http://dongjiu.southeastasia.cloudapp.azure.com
https://dongjiu.southeastasia.cloudapp.azure.com

* powershell
** write-host
https://technet.microsoft.com/en-us/library/ee177031.aspx
* vsts
** variables
https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/release/variables?tabs=batch#default-variables
* .NET Core
** download
https://www.microsoft.com/net/core#windowscmd
** doc
*** core
https://docs.microsoft.com/en-us/dotnet/core/
*** CLI
https://docs.microsoft.com/en-us/dotnet/core/tools/index?tabs=netcore2x
*** tutorial
https://docs.microsoft.com/en-us/dotnet/core/tutorials/
*** deployment
https://docs.microsoft.com/en-us/dotnet/core/deploying/index
https://docs.microsoft.com/en-us/aspnet/core/publishing/?tabs=aspnetcore2x
https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli
$ dotnet publish -c Release -r centos-x64
*** Kestrel
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?tabs=aspnetcore2x
*** bower
https://docs.microsoft.com/en-us/aspnet/core/client-side/bower
** CLI cheatsheet
https://carlos.mendible.com/2017/09/21/net-core-cli-and-msbuild-cheat-sheet/
** project structure
http://www.tutorialsteacher.com/core/aspnet-core-application-project-structure
** directory structure of published apps
https://docs.microsoft.com/en-us/aspnet/core/hosting/directory-structure
** serving static files
http://www.tutorialsteacher.com/core/aspnet-core-static-file
** middleware
http://www.tutorialsteacher.com/core/aspnet-core-middleware
** dependency injection
http://www.tutorialsteacher.com/core/dependency-injection-in-aspnet-core
** environment
http://www.tutorialsteacher.com/core/aspnet-core-environment-variable
https://andrewlock.net/how-to-set-the-hosting-environment-in-asp-net-core/

*** launchSettings.json
used by Visual Studio
https://exceptionnotfound.net/working-with-environments-and-launch-settings-in-asp-net-core/
https://codeopinion.com/environment-variables-asp-net-core/

** Configuration
appSettings.json
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration?tabs=basicconfiguration

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.2" />
  </ItemGroup>

** bundle
https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification

** centos self-contained app
Failed to load xxx, error: libunwind.so.8: cannot open shared object file: No such file or directory
Failed to bind to CoreCLR at '/home/ikriv/bin/dnc/libcoreclr.so'

https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x
http://www.ikriv.com/blog/?p=2438

sudo yum update
sudo yum install libunwind libicu

;; sudo yum install dotnet-sdk-2.0.0

** use nginx
https://docs.microsoft.com/en-us/aspnet/core/publishing/linuxproduction?tabs=aspnetcore2x

** ASP.NET Core
https://docs.microsoft.com/en-us/aspnet/core/

*** RenderSection
https://stackoverflow.com/questions/23327578/what-is-rendersection-in-asp-net-mvc
** code generation
https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates

https://stackoverflow.com/questions/27986147/target-not-running-when-using-beforetargets-build-on-build-server

https://stackoverflow.com/questions/2855713/what-is-the-difference-between-dependsontargets-and-aftertargets
** msbuild targets reference
https://msdn.microsoft.com/en-us/library/7z253716.aspx
https://msdn.microsoft.com/en-us/library/microsoft.build.tasks.aspx
*** dotnet core csproj
https://docs.microsoft.com/en-us/dotnet/core/tools/csproj
*** Message not shown
https://stackoverflow.com/questions/7557562/how-do-i-get-the-message-msbuild-task-to-shows-up-in-the-visual-studio-project
https://social.msdn.microsoft.com/Forums/vstudio/en-US/e546ebd5-0fbd-4cda-acc6-2964698031ab/displaying-console-message-with-the-message-command?forum=msbuild

<Message Importance="High" Text="+++ Justin Dearing +++" />

dotnet build -v n
dotnet build --verbosity normal

*** newline in Message
https://stackoverflow.com/questions/2459994/is-there-a-way-to-print-a-new-line-when-using-message
%0a
*** MSBuild
https://msdn.microsoft.com/en-us/library/z7f65y0d.aspx
*** Exec
https://msdn.microsoft.com/en-us/library/x8zx72cd.aspx
** https
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl
** WebListener
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/weblistener
** password hashing
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction
https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection/
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/consumer-apis/password-hashing

Install-Package Microsoft.AspNetCore.DataProtection -Version 2.0.0 

https://en.wikipedia.org/wiki/PBKDF2
http://www.c-sharpcorner.com/article/hashing-passwords-in-net-core-with-tips/

** mvc
https://docs.microsoft.com/en-us/aspnet/core/mvc/overview
* C#
** expression bodied members (=> in member declarations)
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members

* shell
** execute remote script
https://stackoverflow.com/questions/305035/how-to-use-ssh-to-run-a-shell-script-on-a-remote-machine

ssh root@MachineB 'bash -s' < local_script.sh

** keep process alive when logging out ssh
https://askubuntu.com/questions/8653/how-to-keep-processes-running-after-ending-ssh-session
https://en.wikipedia.org/wiki/Nohup
nohup
tmux
* CentOS
** centos version
https://linuxconfig.org/how-to-check-centos-version
$ hostnamectl
$ rpm --query centos-release
** nginx
https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-centos-7

http://nginx.org/en/docs/beginners_guide.html

$ sudo systemctl start nginx.service
$ sudo systemctl status nginx.service

*** log
https://www.digitalocean.com/community/tutorials/how-to-configure-logging-and-log-rotation-in-nginx-on-an-ubuntu-vps
/var/log/nginx/access.log
/var/log/nginx/error.log

*** proxy_pass, permission denied
https://stackoverflow.com/questions/25235453/nginx-proxy-server-localhost-permission-denied
$ sudo /usr/sbin/setsebool httpd_can_network_connect true 

** ftp
https://stackoverflow.com/questions/16727217/how-can-i-access-ftp-to-centos

$ sudo yum install vsftpd
$ sudo service vsftpd start

check:
$ netstat -an | grep 21
$ netstat -an | grep 22
** file transfer
http://www.server-world.info/en/note?os=CentOS_7&p=ssh&f=2
https://stackoverflow.com/questions/29789364/upload-files-to-centos

*** scp
$ scp ./test.txt cent@www.srv.world:~/ 
$ scp cent@www.srv.world:/home/cent/test.txt ./test.txt

$ scp app.zip donzhu@dongjiu.southeastasia.cloudapp.azure.com:~/app.zip

folder:
$ scp -r user@your.server.example.com:/path/to/foo /home/user/Desktop/

$ scp -r donzhu@dongjiu.southeastasia.cloudapp.azure.com:~/nginxconf nginxconf

$ scp -r /c/Users/donzhu/Documents/programming/dongjiu_web/bin/Release/netcoreapp2.0/centos-x64/publish/ donzhu@dongjiu.southeastasia.cloudapp.azure.com:~/dongjiuweb

*** sftp
$ sftp cent@www.srv.world 
sftp> 
# show current directory on remote server
sftp> pwd
Remote working directory: /home/cent 
# show current directory on local server
sftp> !pwd
/home/redhat 
# show files in current directory on FTP server
sftp> ls -l
drwxrwxr-x    2 cent     cent            6 Jul 29 21:33 public_html
-rw-rw-r--    1 cent     cent           10 Jul 28 22:53 test.txt
# show files in current directory on local server
sftp> !ls -l
total 4
-rw-rw-r-- 1 redhat redhat 10 Jul 29 21:31 test.txt
# change directory
sftp> cd public_html
sftp> pwd
Remote working directory: /home/cent/public_html 
# upload a file to remote server
sftp> put test.txt redhat.txt
Uploading test.txt to /home/cent/redhat.txt
test.txt 100% 10 0.0KB/s 00:00
sftp> ls -l
drwxrwxr-x    2 cent     cent            6 Jul 29 21:33 public_html
-rw-rw-r--    1 cent     cent           10 Jul 29 21:39 redhat.txt
-rw-rw-r--    1 cent     cent           10 Jul 28 22:53 test.txt
# upload some files to remote server
sftp> put *.txt
Uploading test.txt to /home/cent/test.txt
test.txt 100% 10 0.0KB/s 00:00
Uploading test2.txt to /home/cent/test2.txt
test2.txt 100% 0 0.0KB/s 00:00
sftp> ls -l
drwxrwxr-x    2 cent     cent            6 Jul 29 21:33 public_html
-rw-rw-r--    1 cent     cent           10 Jul 29 21:39 redhat.txt
-rw-rw-r--    1 cent     cent           10 Jul 29 21:45 test.txt
-rw-rw-r--    1 cent     cent           10 Jul 29 21:46 test2.txt
# download a file from remote server
sftp> get test.txt
Fetching /home/cent/test.txt to test.txt
/home/cent/test.txt 100% 10 0.0KB/s 00:00 
# download some files from remote server
sftp> get *.txt
Fetching /home/cent/redhat.txt to redhat.txt
/home/cent/redhat.txt 100% 10 0.0KB/s 00:00
Fetching /home/cent/test.txt to test.txt
/home/cent/test.txt 100% 10 0.0KB/s 00:00
Fetching /home/cent/test2.txt to test2.txt
/home/cent/test2.txt 100% 10 0.0KB/s 00:00
# create a directory on remote server
sftp> mkdir testdir
sftp> ls -l
drwxrwxr-x    2 cent     cent            6 Jul 29 21:33 public_html
-rw-rw-r--    1 cent     cent           10 Jul 29 21:39 redhat.txt
-rw-rw-r--    1 cent     cent           10 Jul 29 21:45 test.txt
-rw-rw-r--    1 cent     cent           10 Jul 29 21:46 test2.txt
drwxrwxr-x    2 cent     cent            6 Jul 29 21:53 testdir
# delete a directory on remote server
sftp> rmdir testdir
rmdir ok, `testdir' removed
sftp> ls -l
drwxrwxr-x    2 cent     cent            6 Jul 29 21:33 public_html
-rw-rw-r--    1 cent     cent           10 Jul 29 21:39 redhat.txt
-rw-rw-r--    1 cent     cent           10 Jul 29 21:45 test.txt
-rw-rw-r--    1 cent     cent           10 Jul 29 21:46 test2.txt
# delete a file on remote server
sftp> rm test2.txt
Removing /home/cent/test2.txt
sftp> ls -l
drwxrwxr-x    2 cent     cent            6 Jul 29 21:33 public_html
-rw-rw-r--    1 cent     cent           10 Jul 29 21:39 redhat.txt
-rw-rw-r--    1 cent     cent           10 Jul 29 21:45 test.txt
# execute commands with "![command]"
sftp> !cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
...
...
redhat:x:1001:1001::/home/redhat:/bin/bash
# exit
sftp> quit
221 Goodbye.
*** curl
$ curl ftps://waws-prod-sn1-149.ftp.azurewebsites.windows.net -u dongjiuweb\\donzhu

$ find mydir -type f -exec curl -u xxx:psw --ftp-create-dirs -T {} ftp://192.168.1.158/public/demon_test/{} \;
** firewall
https://wiki.centos.org/HowTos/Network/IPTables
https://www.liquidweb.com/kb/how-to-start-and-enable-firewalld-on-centos-7/
http://ask.xmodulo.com/open-port-firewall-centos-rhel.html

** https
http://nginx.org/en/docs/http/configuring_https_servers.html

https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins

https://www.centos.bz/2011/12/nginx-ssl-https-support/

https://stackoverflow.com/questions/9380403/what-does-ssl-ctx-use-privatekey-file-problems-getting-password-error-indica

https://www.cyberciti.biz/faq/linux-unix-nginx-redirect-all-http-to-https/
https://www.bjornjohansen.no/redirect-to-https-with-nginx
https://serverfault.com/questions/186896/nginx-redirecting-to-localhost
** tips
$ sudo systemctl restart nginx
$ sudo vi .../error.log

refresh browser: ctrl + F5
* ping
** port
https://serverfault.com/questions/309357/ping-a-specific-port
nmap -p 80 example.com
* software engineering
** release life cycle
https://en.wikipedia.org/wiki/Software_release_life_cycle
