create table province (
    province_name nvarchar(20) not null,
    abbreviation nvarchar(1) not null,
    primary key (province_name)
);

create table vehicle_plate_letter (
    province_name nvarchar(20) not null,
    letter varchar(1) not null,
    description nvarchar(200) not null,
    primary key (province_name, letter),
    constraint Province_Assigns_VehiclePlateLetter
        foreign key (province_name)
        references province (province_name)
);

insert into province (province_name, abbreviation) values (N'北京市', N'京');
insert into vehicle_plate_letter (province_name, letter, description) values (N'北京市', 'A', N'城区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'北京市', 'B', N'出租车');
insert into vehicle_plate_letter (province_name, letter, description) values (N'北京市', 'C', N'城区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'北京市', 'E', N'城区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'北京市', 'F', N'城区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'北京市', 'G', N'远郊区县');
insert into vehicle_plate_letter (province_name, letter, description) values (N'北京市', 'H', N'城区');

insert into province (province_name, abbreviation) values (N'天津市', N'津');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'A', N'公交车、公安车');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'B', N'市区号牌');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'C', N'市区号牌');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'D', N'市区号牌');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'E', N'出租车');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'F', N'市区号牌');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'G', N'市区号牌');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'H', N'市区号牌');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'J', N'市区号牌');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'K', N'市区号牌');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'L', N'市区号牌');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'M', N'市区号牌');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'N', N'市区号牌');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'Q', N'市区号牌');
insert into vehicle_plate_letter (province_name, letter, description) values (N'天津市', 'R', N'市区号牌');

insert into province (province_name, abbreviation) values (N'河北省', N'冀');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河北省', 'A', N'石家庄市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河北省', 'B', N'唐山市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河北省', 'C', N'秦皇岛市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河北省', 'D', N'邯郸市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河北省', 'E', N'邢台市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河北省', 'F', N'保定市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河北省', 'G', N'张家口市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河北省', 'H', N'承德市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河北省', 'J', N'沧州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河北省', 'R', N'廊坊市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河北省', 'T', N'衡水市');

insert into province (province_name, abbreviation) values (N'山西省', N'晋');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山西省', 'A', N'太原市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山西省', 'B', N'大同市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山西省', 'C', N'阳泉市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山西省', 'D', N'长治市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山西省', 'E', N'晋城市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山西省', 'F', N'朔州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山西省', 'H', N'忻州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山西省', 'J', N'吕梁市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山西省', 'K', N'晋中市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山西省', 'L', N'临汾市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山西省', 'M', N'运城市');

insert into province (province_name, abbreviation) values (N'内蒙古自治区', N'蒙');
insert into vehicle_plate_letter (province_name, letter, description) values (N'内蒙古自治区', 'A', N'呼和浩特市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'内蒙古自治区', 'B', N'包头市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'内蒙古自治区', 'C', N'乌海市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'内蒙古自治区', 'D', N'赤峰市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'内蒙古自治区', 'E', N'呼伦贝尔市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'内蒙古自治区', 'F', N'兴安盟');
insert into vehicle_plate_letter (province_name, letter, description) values (N'内蒙古自治区', 'G', N'通辽市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'内蒙古自治区', 'H', N'锡林郭勒盟');
insert into vehicle_plate_letter (province_name, letter, description) values (N'内蒙古自治区', 'J', N'乌兰察布市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'内蒙古自治区', 'K', N'鄂尔多斯市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'内蒙古自治区', 'L', N'巴彦淖尔市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'内蒙古自治区', 'M', N'阿拉善盟');

insert into province (province_name, abbreviation) values (N'辽宁省', N'辽');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'A', N'沈阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'B', N'大连市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'C', N'鞍山市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'D', N'抚顺市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'E', N'本溪市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'F', N'丹东市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'G', N'锦州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'H', N'营口市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'J', N'阜新市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'K', N'辽阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'L', N'盘锦市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'M', N'铁岭市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'N', N'朝阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'辽宁省', 'P', N'葫芦岛市');

insert into province (province_name, abbreviation) values (N'吉林省', N'吉');
insert into vehicle_plate_letter (province_name, letter, description) values (N'吉林省', 'A', N'长春市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'吉林省', 'B', N'吉林市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'吉林省', 'C', N'四平市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'吉林省', 'D', N'辽源市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'吉林省', 'E', N'通化市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'吉林省', 'F', N'白山市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'吉林省', 'G', N'白城市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'吉林省', 'H', N'延边朝鲜族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'吉林省', 'J', N'松原市');

insert into province (province_name, abbreviation) values (N'黑龙江省', N'黑');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'A', N'哈尔滨市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'B', N'齐齐哈尔市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'C', N'牡丹江市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'D', N'佳木斯市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'E', N'大庆市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'F', N'伊春市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'G', N'鸡西市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'H', N'鹤岗市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'J', N'双鸭山市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'K', N'七台河市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'L', N'松花江地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'M', N'绥化市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'N', N'黑河市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'P', N'大兴安岭地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'黑龙江省', 'R', N'省农垦系统');

insert into province (province_name, abbreviation) values (N'上海市', N'沪');
insert into vehicle_plate_letter (province_name, letter, description) values (N'上海市', 'A', N'城区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'上海市', 'B', N'城区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'上海市', 'C', N'远郊区县');
insert into vehicle_plate_letter (province_name, letter, description) values (N'上海市', 'D', N'城区');

insert into province (province_name, abbreviation) values (N'江苏省', N'苏');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江苏省', 'A', N'南京市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江苏省', 'B', N'无锡市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江苏省', 'C', N'徐州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江苏省', 'D', N'常州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江苏省', 'E', N'苏州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江苏省', 'F', N'南通市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江苏省', 'G', N'连云港市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江苏省', 'H', N'淮安市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江苏省', 'J', N'盐城市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江苏省', 'K', N'扬州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江苏省', 'L', N'镇江市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江苏省', 'M', N'泰州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江苏省', 'N', N'宿迁市');

insert into province (province_name, abbreviation) values (N'浙江省', N'浙');
insert into vehicle_plate_letter (province_name, letter, description) values (N'浙江省', 'A', N'杭州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'浙江省', 'B', N'宁波市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'浙江省', 'C', N'温州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'浙江省', 'D', N'绍兴市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'浙江省', 'E', N'湖州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'浙江省', 'F', N'嘉兴市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'浙江省', 'G', N'金华市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'浙江省', 'H', N'衢州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'浙江省', 'J', N'台州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'浙江省', 'K', N'丽水市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'浙江省', 'L', N'舟山市');

insert into province (province_name, abbreviation) values (N'安徽省', N'皖');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'A', N'合肥市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'B', N'芜湖市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'C', N'蚌埠市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'D', N'淮南市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'E', N'马鞍山市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'F', N'淮北市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'G', N'铜陵市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'H', N'安庆市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'J', N'黄山市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'K', N'阜阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'L', N'宿州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'M', N'滁州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'N', N'六安市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'P', N'宣城市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'Q', N'巢湖市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'R', N'池州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'安徽省', 'S', N'亳州市');

insert into province (province_name, abbreviation) values (N'福建省', N'闽');
insert into vehicle_plate_letter (province_name, letter, description) values (N'福建省', 'A', N'福州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'福建省', 'B', N'莆田市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'福建省', 'C', N'泉州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'福建省', 'D', N'厦门市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'福建省', 'E', N'漳州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'福建省', 'F', N'龙岩市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'福建省', 'G', N'三明市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'福建省', 'H', N'南平市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'福建省', 'J', N'宁德市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'福建省', 'K', N'省直系统');

insert into province (province_name, abbreviation) values (N'江西省', N'赣');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江西省', 'A', N'南昌市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江西省', 'B', N'赣州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江西省', 'C', N'宜春市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江西省', 'D', N'吉安市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江西省', 'E', N'上饶市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江西省', 'F', N'抚州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江西省', 'G', N'九江市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江西省', 'H', N'景德镇市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江西省', 'J', N'萍乡市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江西省', 'K', N'新余市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江西省', 'L', N'鹰潭市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'江西省', 'M', N'省直系统');

insert into province (province_name, abbreviation) values (N'山东省', N'鲁');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'A', N'济南市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'B', N'青岛市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'C', N'淄博市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'D', N'枣庄市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'E', N'东营市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'F', N'烟台市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'G', N'潍坊市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'H', N'济宁市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'J', N'泰安市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'K', N'威海市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'L', N'日照市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'M', N'滨州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'N', N'德州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'P', N'聊城市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'Q', N'临沂市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'R', N'菏泽市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'S', N'莱芜市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'U', N'青岛市增补');
insert into vehicle_plate_letter (province_name, letter, description) values (N'山东省', 'V', N'潍坊市增补');

insert into province (province_name, abbreviation) values (N'河南省', N'豫');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'A', N'郑州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'B', N'开封市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'C', N'洛阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'D', N'平顶山市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'E', N'安阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'F', N'鹤壁市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'G', N'新乡市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'H', N'焦作市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'J', N'濮阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'K', N'许昌市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'L', N'漯河市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'M', N'三门峡市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'N', N'商丘市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'P', N'周口市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'Q', N'驻马店市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'R', N'南阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'S', N'信阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'河南省', 'U', N'济源市');

insert into province (province_name, abbreviation) values (N'湖北省', N'鄂');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'A', N'武汉市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'B', N'黄石市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'C', N'十堰市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'D', N'荆州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'E', N'宜昌市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'F', N'襄樊市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'G', N'鄂州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'H', N'荆门市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'J', N'黄冈市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'K', N'孝感市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'L', N'咸宁市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'M', N'仙桃市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'N', N'潜江市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'P', N'神农架林区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'Q', N'恩施土家族苗族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'R', N'天门市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖北省', 'S', N'随州市');

insert into province (province_name, abbreviation) values (N'湖南省', N'湘');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'A', N'长沙市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'B', N'株洲市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'C', N'湘潭市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'D', N'衡阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'E', N'邵阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'F', N'岳阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'G', N'张家界市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'H', N'益阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'J', N'常德市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'K', N'娄底市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'L', N'郴州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'M', N'永州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'N', N'怀化市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'湖南省', 'U', N'湘西土家族苗族自治州');

insert into province (province_name, abbreviation) values (N'广东省', N'粤');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'A', N'广州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'B', N'深圳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'C', N'珠海市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'D', N'汕头市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'E', N'佛山市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'F', N'韶关市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'G', N'湛江市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'H', N'肇庆市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'J', N'江门市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'K', N'茂名市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'L', N'惠州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'M', N'梅州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'N', N'汕尾市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'P', N'河源市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'Q', N'阳江市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'R', N'清远市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'S', N'东莞市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'T', N'中山市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'U', N'潮州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'V', N'揭阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'W', N'云浮市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'X',N'佛山市顺德区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'Y',N'佛山市南海区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广东省', 'Z', N'入境港澳机动车辆');

insert into province (province_name, abbreviation) values (N'广西壮族自治区', N'桂');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'A', N'南宁市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'B', N'柳州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'C', N'桂林市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'D', N'梧州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'E', N'北海市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'F', N'南宁地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'G', N'柳州地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'H', N'桂林地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'J', N'贺州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'K', N'玉林市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'L',N'百色市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'M', N'河池市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'N', N'钦州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'P', N'防城港市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'广西壮族自治区', 'R', N'贵港市');

insert into province (province_name, abbreviation) values (N'海南省', N'琼');
insert into vehicle_plate_letter (province_name, letter, description) values (N'海南省', 'A', N'海口市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'海南省', 'B', N'三亚市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'海南省', 'C', N'琼北车辆管理所：琼山市（已并入海口市）、儋州市、琼海市、万宁市、文昌市、澄迈县、屯昌县、定安县、临高县');
insert into vehicle_plate_letter (province_name, letter, description) values (N'海南省', 'D', N'琼南车辆管理所：五指山市、东方市、白沙黎族自治县、昌江黎族自治县、陵水黎族自治县、乐东黎族自治县、保亭黎族苗族自治县、琼中黎族苗族自治县');
insert into vehicle_plate_letter (province_name, letter, description) values (N'海南省', 'E', N'洋浦开发区');

insert into province (province_name, abbreviation) values (N'重庆市', N'渝');
insert into vehicle_plate_letter (province_name, letter, description) values (N'重庆市', 'A', N'直属车辆管理所：主城区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'重庆市', 'B', N'江南车辆管理分所：主城区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'重庆市', 'C', N'永川车辆管理所：永川市、江津市、合川市、潼南县、铜梁县、璧山县、大足县、綦江县、荣昌县');
insert into vehicle_plate_letter (province_name, letter, description) values (N'重庆市', 'F', N'万州车辆管理所：万州区、梁平县、城口县、巫山县、巫溪县、忠 县、开 县、奉节县、云阳县');
insert into vehicle_plate_letter (province_name, letter, description) values (N'重庆市', 'G', N'涪陵车辆管理所：涪陵区、南川市、垫江县、丰都县、武隆县');
insert into vehicle_plate_letter (province_name, letter, description) values (N'重庆市', 'H', N'黔江车辆管理所：黔江区、石柱土家族自治县、秀山土家族苗族自治县、酉阳土家族苗族自治县、彭水苗族土家族自治县');

insert into province (province_name, abbreviation) values (N'四川省', N'川');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'A', N'成都市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'B', N'绵阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'C', N'自贡市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'D', N'攀枝花市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'E', N'泸州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'F', N'德阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'H', N'广元市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'J', N'遂宁市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'K', N'内江市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'L', N'乐山市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'M', N'资阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'Q', N'宜宾市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'R', N'南充市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'S', N'达州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'T', N'雅安市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'U', N'阿坝藏族羌族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'V', N'甘孜藏族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'W', N'凉山彝族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'X', N'广安市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'Y', N'巴中市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'四川省', 'Z', N'眉山市');

insert into province (province_name, abbreviation) values (N'贵州省', N'贵');
insert into vehicle_plate_letter (province_name, letter, description) values (N'贵州省', 'A', N'贵阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'贵州省', 'B', N'六盘水市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'贵州省', 'C', N'遵义市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'贵州省', 'D', N'铜仁地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'贵州省', 'E', N'黔西南布依族苗族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'贵州省', 'F', N'毕节地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'贵州省', 'G', N'安顺市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'贵州省', 'H', N'黔东南苗族侗族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'贵州省', 'J', N'黔南布依族苗族自治州');

insert into province (province_name, abbreviation) values (N'云南省', N'云');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'A', N'昆明市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'C', N'昭通市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'D', N'曲靖市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'E', N'楚雄彝族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'F', N'玉溪市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'G', N'红河哈尼族彝族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'H', N'文山壮族苗族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'J', N'思茅市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'S', N'临沧市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'K', N'西双版纳傣族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'L', N'大理白族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'M', N'保山市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'N', N'德宏傣族景颇族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'P', N'丽江市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'Q', N'怒江傈僳族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'云南省', 'R', N'迪庆藏族自治州');

insert into province (province_name, abbreviation) values (N'西藏自治区', N'藏');
insert into vehicle_plate_letter (province_name, letter, description) values (N'西藏自治区', 'A', N'拉萨市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'西藏自治区', 'B', N'昌都地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'西藏自治区', 'C', N'山南地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'西藏自治区', 'D', N'日喀则地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'西藏自治区', 'E', N'那曲地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'西藏自治区', 'F', N'阿里地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'西藏自治区', 'G', N'林芝地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'西藏自治区', 'H', N'驻四川省天全县车辆管理所');
insert into vehicle_plate_letter (province_name, letter, description) values (N'西藏自治区', 'J', N'驻青海省格尔木市车辆管理所');

insert into province (province_name, abbreviation) values (N'陕西省', N'陕');
insert into vehicle_plate_letter (province_name, letter, description) values (N'陕西省', 'A', N'西安市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'陕西省', 'B', N'铜川市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'陕西省', 'C', N'宝鸡市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'陕西省', 'D', N'咸阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'陕西省', 'E', N'渭南市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'陕西省', 'F', N'汉中市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'陕西省', 'G', N'安康市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'陕西省', 'H', N'商洛市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'陕西省', 'J', N'延安市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'陕西省', 'K', N'榆林市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'陕西省', 'U', N'省直系统');
insert into vehicle_plate_letter (province_name, letter, description) values (N'陕西省', 'V', N'杨凌高新农业示范区');

insert into province (province_name, abbreviation) values (N'甘肃省', N'甘');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'A', N'兰州市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'B', N'嘉峪关市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'C', N'金昌市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'D', N'白银市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'E', N'天水市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'F', N'酒泉市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'G', N'张掖市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'H', N'武威市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'J', N'定西市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'K', N'陇南市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'L', N'平凉市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'M', N'庆阳市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'N', N'临夏回族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'甘肃省', 'P', N'甘南藏族自治州');

insert into province (province_name, abbreviation) values (N'青海省', N'青');
insert into vehicle_plate_letter (province_name, letter, description) values (N'青海省', 'A', N'西宁市');
insert into vehicle_plate_letter (province_name, letter, description) values (N'青海省', 'B', N'海东地区');
insert into vehicle_plate_letter (province_name, letter, description) values (N'青海省', 'C', N'海北藏族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'青海省', 'D', N'黄南藏族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'青海省', 'E', N'海南藏族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'青海省', 'F', N'果洛藏族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'青海省', 'G', N'玉树藏族自治州');
insert into vehicle_plate_letter (province_name, letter, description) values (N'青海省', 'H', N'海西蒙古族藏族自治州');
